### ISSUE TITLE
Meaning of the symbols on the track list 

### ISSUE THREAD

**Issue by aritorhamo** [tari01/odio#3]
Hello,

I wonder what's the meaning of the symbols on the second column from the left on the track list. They look like black play and stop buttons, but they do nothing, and I can see no apparent purpose for them. I wouldn't perhaps have asked otherwise, but the symbols are sometimes arranged differently for tracks on the same album. I can come up with no reason what might trigger the difference. For most tracks the symbols are arranged stop-play, but for some the arrangement is (left) play-stop or stop-stop. 

Thanks!

P.S. I saw the suggestion to to add a question label to the issue, but I wasn't able to find a way to do it.

**Comment by tari01** [comment]
@aritorhamo 

The symbols represent the result of Odio's silence detection: the first one is the beginning of the file, the second is the end. The triangle means Odio detected and removed silence, the square means there was no silence to remove.

I am a bit puzzled, because you should normally not see this column - it is only visible in debugging mode. Can you tell me which OS/version + Odio version you are using?

**Comment by aritorhamo** [comment]
Thanks for the quick reply. Nothing to worry about then. I'm using Odio in Linux Mint 20.1. The exact Odio version is "20.5.21.244~ubuntu18.04.1".

**Comment by tari01** [comment]
OK, I'm closing this then. I am always building new Ubuntu versions back to the last LTS release (20.04 right now). This explains why you are stuck with such an old one.
